name: CI
on:
  push:
    branches:
      - master
jobs:
  deploy-on-heroku:
    runs-on: ubuntu-latest
    steps:
      - name: uname
        run: uname -a
      - name: Deploy to Render.com
        run: echo "Follow deployment on Render.com https://dashboard.render.com/"
