name: monitoring
on:
  schedule:
    - cron: '20 23 * * *'
jobs:
  run-health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install project
        run: yarn
      - name: Run health check
        run: yarn simple-puppeteer-uptime-checker
